// Generated by CoffeeScript 1.6.3
var all, asSeq, deepEqual, drop, dropWhile, equal, filter, fold, join, lazy, map, mapCat, ok, produced, reduced, repeat, resolve, scan, series, take, takeWhile, _ref, _ref1, _ref2;

_ref = require('assert'), deepEqual = _ref.deepEqual, equal = _ref.equal, ok = _ref.ok;

_ref1 = require('./index'), asSeq = _ref1.asSeq, lazy = _ref1.lazy, repeat = _ref1.repeat, map = _ref1.map, scan = _ref1.scan, fold = _ref1.fold, series = _ref1.series, take = _ref1.take, drop = _ref1.drop, takeWhile = _ref1.takeWhile, dropWhile = _ref1.dropWhile, filter = _ref1.filter, join = _ref1.join, mapCat = _ref1.mapCat, reduced = _ref1.reduced, produced = _ref1.produced;

_ref2 = require('kew'), resolve = _ref2.resolve, all = _ref2.all;

describe('creating seqs with asSeq', function() {
  var sum;
  sum = function(seq) {
    return reduced(seq, (function(v, a) {
      return a + v;
    }), 0);
  };
  it('creates a seq from an array', function(done) {
    return (sum(asSeq([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))).then(function(x) {
      return equal(x, 55);
    }).fin(done).end();
  });
  it('creates a seq from a value', function(done) {
    return (sum(asSeq(10))).then(function(x) {
      return equal(x, 10);
    }).fin(done).end();
  });
  it('creates an empty seq from undethened', function(done) {
    return (sum(asSeq())).then(function(x) {
      return equal(x, 0);
    }).fin(done).end();
  });
  it('creates an empty seq from null', function(done) {
    return (sum(asSeq())).then(function(x) {
      return equal(x, 0);
    }).fin(done).end();
  });
  return it('creates a seq from a promise', function(done) {
    return (sum(asSeq(resolve(10)))).then(function(x) {
      return equal(x, 10);
    }).fin(done).end();
  });
});

describe('combinators', function() {
  it('provides map', function(done) {
    var seq;
    seq = map([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], function(v) {
      return v + 1;
    });
    return produced(seq).then(function(v) {
      return deepEqual(v, [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]);
    }).fin(done).end();
  });
  it('provides scan', function(done) {
    var seq;
    seq = scan([1, 2, 3, 4, 5], (function(v, a) {
      return v + a;
    }), 0);
    return produced(seq).then(function(v) {
      return deepEqual(v, [1, 3, 6, 10, 15]);
    }).fin(done).end();
  });
  it('provides fold', function(done) {
    var seq;
    seq = fold([1, 2, 3, 4, 5], (function(v, a) {
      return v + a;
    }), 0);
    return reduced(seq).then(function(v) {
      return equal(v, 15);
    }).fin(done).end();
  });
  describe('take', function() {
    it('takes some number of elements from the start', function(done) {
      var seq;
      seq = take([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 5);
      return produced(seq).then(function(v) {
        return deepEqual(v, [1, 2, 3, 4, 5]);
      }).fin(done).end();
    });
    return it('can take no elements', function(done) {
      var seq;
      seq = take([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 0);
      return produced(seq).then(function(v) {
        return deepEqual(v, []);
      }).fin(done).end();
    });
  });
  describe('drop', function() {
    it('drop some number of elements from the start', function(done) {
      var seq;
      seq = drop([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 5);
      return produced(seq).then(function(v) {
        return deepEqual(v, [6, 7, 8, 9, 10]);
      }).fin(done).end();
    });
    return it('can drop no elements', function(done) {
      var seq;
      seq = drop([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 0);
      return produced(seq).then(function(v) {
        return deepEqual(v, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);
      }).fin(done).end();
    });
  });
  it('provides takeWhile', function(done) {
    var seq;
    seq = takeWhile([1, 2, 3, 4, 5, 6, 7, 8, 9, 10].concat([1, 2]), function(v) {
      return v < 6;
    });
    return produced(seq).then(function(v) {
      return deepEqual(v, [1, 2, 3, 4, 5]);
    }).fin(done).end();
  });
  it('provides dropWhile', function(done) {
    var seq;
    seq = dropWhile([1, 2, 3, 4, 5, 6, 7, 8, 9, 10].concat([1, 2]), function(v) {
      return v < 6;
    });
    return produced(seq).then(function(v) {
      return deepEqual(v, [6, 7, 8, 9, 10].concat([1, 2]));
    }).fin(done).end();
  });
  it('provides filter', function(done) {
    var seq;
    seq = filter([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], function(v) {
      return v % 2 === 0;
    });
    return produced(seq).then(function(v) {
      return deepEqual(v, [2, 4, 6, 8, 10]);
    }).fin(done).end();
  });
  it('provides join', function(done) {
    var c1, c2, c3;
    c1 = produced(join([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])).then(function(v) {
      return deepEqual(v, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);
    });
    c2 = produced(join([1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map(function(v) {
      return [v];
    }))).then(function(v) {
      return deepEqual(v, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);
    });
    c3 = produced(join([1, [2], 3])).then(function(v) {
      return deepEqual(v, [1, 2, 3]);
    });
    return all([c1, c2, c3]).fin(done).end();
  });
  it('provides mapCat', function(done) {
    var c1, c2, seq;
    seq = mapCat([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], function(x) {
      return [x];
    });
    c1 = produced(seq).then(function(v) {
      return deepEqual(v, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);
    });
    seq = mapCat([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], function(x) {
      if (x % 2 === 0) {
        return [x];
      } else {
        return x;
      }
    });
    c2 = produced(seq).then(function(v) {
      return deepEqual(v, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);
    });
    return all([c1, c2]).fin(done).end();
  });
  it('provides repeat', function(done) {
    var seq;
    seq = repeat(10);
    return produced(take(seq, 5)).then(function(v) {
      return deepEqual(v, [10, 10, 10, 10, 10]);
    }).fin(done).end();
  });
  return it('provides series', function(done) {
    var seq;
    seq = series((function(v) {
      return v + 1;
    }), 0);
    return produced(take(seq, 10)).then(function(v) {
      return deepEqual(v, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);
    }).fin(done).end();
  });
});

describe('lazy', function() {
  return it('can defer collection creation', function(done) {
    var seq;
    seq = lazy(function() {
      return [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
    });
    return produced(seq).then(function(v) {
      return deepEqual(v, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);
    }).fin(done).end();
  });
});
